name: la3eeb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  arabic_font: ^0.0.9
  easy_stepper: ^0.8.5
  flutter:
    sdk: flutter
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/la3eeb.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - images/
